chore: use newTokens for search [B1M2-5050]
coingaming/moon-design pull request #1570
Opened 2022-01-21 10:53 UTC by alexisdevtailor

2022-01-31 13:50 UTC, dkireev requested changes
some properties have numbers where should be pixels. Somewhere old tokens are still in use

2022-02-02 16:00 UTC, dkireev requested changes
settings applied without rem function

2022-02-03 16:47 UTC, dkireev requested changes

2022-02-03 16:47 UTC, dkireev commented on packages/core/src/search/private/components/Input.ts
> +  transitionDuration: newTokens.transitionDuration,
There is no transitionDuration token anymore

2022-02-04 09:10 UTC, dkireev requested changes

2022-02-04 09:10 UTC, dkireev commented on packages/core/src/search/private/components/Input.ts
> +    transitionDuration,
No, it's an old token. Either replace it with a hardcode, or re-think transition and transitionDuration

2022-02-04 11:14 UTC, karl-kallavus commented
@alexisdevtailor please update tests

2022-02-04 11:14 UTC, karl-kallavus requested changes
Please update tests

2022-02-04 12:57 UTC, dkireev approved these changes

2022-02-07 11:18 UTC, merged