chore: Make radioButton rtl friendly [B1M2-5104]
coingaming/moon-design pull request #1592
Opened 2022-01-31 06:02 UTC by alexisdevtailor

2022-02-01 05:44 UTC, karl-kallavus requested changes

2022-02-01 05:44 UTC, karl-kallavus commented on next-docs/public/examples/datePicker/__tests__/__snapshots__/index.test.tsx.snap
> +              className="DayContainer-l4w9ci-0 coSdBl"
These tests should be fine now. Please merge fresh develop into your branch

2022-02-01 05:44 UTC, karl-kallavus commented on packages/core/src/radioButton/styles/RadioButtonCaption.ts
> +  marginInlineStart: theme.newTokens.space.xsmall,
please resolve the merge conflict here

2022-02-01 17:01 UTC, yarema184 approved these changes

2022-02-02 08:57 UTC, karl-kallavus approved these changes

2022-02-02 08:57 UTC, merged