feat: Added segmente control
coingaming/moon-design pull request #1899
Opened 2022-09-16 10:05 UTC by filip-andjelic

2022-09-16 15:41 UTC, karl-kallavus requested changes
Do we need to regenerate CSS files as well?

2022-09-16 15:41 UTC, karl-kallavus commented on next-docs/public/examples/tabsTW/SegmentControl.tsx
> +          {items.map((item:any) => {
use proper type here

2022-09-16 15:41 UTC, karl-kallavus commented on next-docs/public/examples/tabsTW/SegmentControl.tsx
> +                        ? 'bg-gohan text-black rounded-lg px-3 py-2 focus:border-none '
please setup proper linter

2022-09-19 08:57 UTC, yarema184 commented on next-docs/public/examples/tabsTW/SegmentControl.tsx
> +                        ? 'bg-gohan text-black rounded-lg px-3 py-2 focus:border-none '
Please use text color from moon tokens `text-bulma`

2022-09-19 08:57 UTC, yarema184 commented on next-docs/public/examples/tabsTW/SegmentControl.tsx
> +                    <p className="leading-6 self-left"> {item} </p>
I think it's better to use the `span` inside the `button`.

2022-09-19 13:33 UTC, dkireev requested changes

2022-09-19 13:33 UTC, dkireev commented on next-docs/public/examples/tabsTW/SegmentControl.tsx
> +        <Tab.List className="flex h-10 p-1 bg-beerus rounded-xl">
Please, use moon radiuses. in this case it's interactive. Never use TW radiuses and font sizes, where it's possible to use moon ones.

2022-09-19 13:33 UTC, dkireev commented on next-docs/public/examples/tabsTW/SegmentControl.tsx
> +              <div className="mr-1">
Also, it's always better to use ms, ps, me, and pe. Instead of corresponding ml, pl, mr, and pr. Start and end are more suitable for rtl

2022-10-19 13:38 UTC, closed without merging