Base1 3301
coingaming/moon-design pull request #1963
Opened 2022-11-07 13:09 UTC by OladetounJed

## Screenshot and description

## Checklist

- [ ] You attached screenshots or added description about changes
- [ ] You use [conventional commits naming](https://www.conventionalcommits.org/en/v1.0.0/), e.g. `fix: your changes description [TicketNumber]`, `feat: your feature name [TicketNumber]`
- [ ] You have updated the documentation accordingly.

2022-11-07 13:12 UTC, OladetounJed commented
@yarema184 , here is PR.

The issues are

- Animation doesn't seems to work even after setting the keyframes on the preset file

- setOpen needs improvement

I will refactor and improve the docs once everything is set

2022-11-08 13:25 UTC, karl-kallavus requested changes

2022-11-08 13:25 UTC, karl-kallavus commented on next-docs/public/examples/snackbarTW/Default.tsx
> +  const openSnackbarHandler = (type: string) => {
use React.useCallback

2022-11-08 13:25 UTC, karl-kallavus commented on next-docs/public/examples/snackbarTW/Default.tsx
> +      <Button onClick={() => openSnackbarHandler('default')}>
pass here a callback created by useCallback

2022-11-08 13:25 UTC, karl-kallavus commented on next-docs/public/examples/snackbarTW/SnackbarPositions.tsx
> +      <Button onClick={() => openSnackbarHandler('top-right')}>Top Right Snackbar</Button>
same here and below

2022-11-14 10:37 UTC, merged