Feat/combobox
coingaming/moon-design pull request #2203
Opened 2023-04-28 08:41 UTC by karl-kallavus

## Screenshot and description

## Checklist

- [ ] You attached screenshots or added description about changes
- [ ] You use [conventional commits naming](https://www.conventionalcommits.org/en/v1.0.0/), e.g. `fix: your changes description [TicketNumber]`, `feat: your feature name [TicketNumber]`
- [ ] You have updated the documentation accordingly.

2023-04-28 11:16 UTC, karl-kallavus commented on workspaces/core/src/combobox/Combobox.tsx
> +          size === undefined || size === 'md' ? 'text-base' : `text-${size}`,
`text-${size}`

2023-04-28 11:17 UTC, karl-kallavus commented on workspaces/core/src/combobox/Combobox.tsx
> +      <InputInset.Label className='w-auto top-[-.125rem] !right-0 !left-0 whitespace-nowrap overflow-x-hidden'>{label}</InputInset.Label>
0.5

2023-04-28 11:18 UTC, karl-kallavus commented on workspaces/core/src/combobox/Combobox.tsx
> +          menuWidth ? menuWidth : 'w-full max-h-[18.75rem] py-2 px-1 my-1 rounded-moon-s-md box-border bg-gohan shadow-moon-lg z-10 absolute',
h-72

2023-04-28 11:20 UTC, karl-kallavus commented on next-docs/public/examples/combobox/Default.tsx
> +              <Combobox.Options className={'min-w-[18.75rem] z-10000'}>
z-50

2023-04-28 11:22 UTC, karl-kallavus commented on next-docs/public/examples/combobox/InsetSelectStates.tsx
> +                  <div className='relative cursor-default select-none py-2 px-4 text-gray-700'>
text-gray-700 -> text-trunks

2023-04-28 11:28 UTC, yarema184 requested changes

2023-04-28 11:28 UTC, yarema184 commented on workspaces/core/src/combobox/Combobox.tsx
> +          ref={ref as React.Ref<HTMLElement>}
Can we avoid type assertions here?

2023-04-28 11:28 UTC, yarema184 commented on workspaces/core/src/combobox/Combobox.tsx
> +        (size === 'xl' || (innerLabel !== undefined && innerLabel)) && 'py-3 px-4 rounded-xl gap-x-4',
I think it makes sense to put this in a separate helper `getSize(),` to make code more clearly readable

2023-04-28 11:28 UTC, yarema184 commented on workspaces/core/src/combobox/Combobox.tsx
> +            && 'pt-[.75rem] input-xl-dt-label',
please replace ` pt-[.75rem]` with `pt-3`

2023-04-28 11:28 UTC, yarema184 commented on workspaces/core/src/combobox/Combobox.tsx
> +        multiple={multiple !== undefined}
if `multiple = true,` always by default, does this check make sense? And at all, could multiple be false in this subcomponent?

2023-04-28 11:28 UTC, yarema184 commented on next-docs/public/examples/combobox/Default.tsx
> +                  <div className='relative cursor-default select-none py-2 px-4 text-gray-700'>
Let's use moon colors for examples as well

2023-04-28 11:28 UTC, yarema184 commented on next-docs/public/examples/combobox/Default.tsx
> +                  <div className='relative cursor-default select-none py-2 px-4 text-gray-700'>
Let's use moon colors for examples as well

2023-05-04 10:56 UTC, yarema184 commented on workspaces/core/src/combobox/Combobox.tsx
> +        size === 'sm' && 'w-4 h-4',
perhaps it makes sense to combine in one condition, like: 
`size === 'sm' ? 'w-4 h-4 text-moon-16' : 'text-moon-24',`

2023-05-04 11:13 UTC, merged